version: "3.3"

services:
  mongo:
    image: mongo
    volumes:
      - data:/opt/mongodb/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: mongodb
    ports:
      - "27017:27017"
  cache:
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - cache:/data

volumes:
  data: {}
  cache:
    driver: local